version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
