"""Added role to AdminUser

Revision ID: 300ca53aa7e6
Revises: d576e5f44e5d
Create Date: 2020-07-14 15:29:50.744965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '300ca53aa7e6'
down_revision = 'd576e5f44e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'adminuser',
        sa.Column('role', sa.String(length=50))
    )
    role = table('adminuser', column('role'))
    op.execute(role.update().values(role='regular'))
    op.alter_column('adminuser', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adminuser', 'role')
    # ### end Alembic commands ###
