"""empty message

Revision ID: 478a85cec46f
Revises: ca1e7cbe23f3
Create Date: 2020-07-01 04:18:03.919087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478a85cec46f'
down_revision = 'ca1e7cbe23f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'survey',
        sa.Column(
            'cover_image_file',
            sa.LargeBinary(),
            nullable=True
        )
    )
    op.add_column(
        'survey',
        sa.Column(
            'cover_image_type',
            sa.String(length=4),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'cover_image_type')
    op.drop_column('survey', 'cover_image_file')
    # ### end Alembic commands ###
