"""empty message

Revision ID: d576e5f44e5d
Revises: ad7ccd663c44
Create Date: 2020-07-07 21:51:55.972317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd576e5f44e5d'
down_revision = 'ad7ccd663c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('illness_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnosis', 'illness', ['illness_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnosis', type_='foreignkey')
    op.drop_column('diagnosis', 'illness_id')
    # ### end Alembic commands ###
