"""empty message

Revision ID: 72bd108be853
Revises: 12ba81140ab8
Create Date: 2020-06-01 16:36:31.309158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bd108be853'
down_revision = '12ba81140ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('image_link', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summary', 'image_link')
    # ### end Alembic commands ###
