"""empty message

Revision ID: 9b5b2c5d3aef
Revises: 72bd108be853
Create Date: 2020-06-02 15:45:35.699468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5b2c5d3aef'
down_revision = '72bd108be853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('root_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey', 'question', ['root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'root_id')
    # ### end Alembic commands ###
