"""empty message

Revision ID: a8e0ca3b4af9
Revises: f613a23f2f69
Create Date: 2020-06-22 14:54:18.874472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e0ca3b4af9'
down_revision = 'f613a23f2f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('image_file', sa.LargeBinary(), nullable=True))
    op.add_column('link', sa.Column('image_type', sa.String(length=4), nullable=True))
    op.drop_column('link', 'image_link')
    op.add_column('summary', sa.Column('image_file', sa.LargeBinary(), nullable=True))
    op.add_column('summary', sa.Column('image_type', sa.String(length=4), nullable=True))
    op.drop_column('summary', 'image_link')
    op.add_column('survey', sa.Column('image_file', sa.LargeBinary(), nullable=True))
    op.add_column('survey', sa.Column('image_type', sa.String(length=4), nullable=True))
    op.drop_column('survey', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('image_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('survey', 'image_type')
    op.drop_column('survey', 'image_file')
    op.add_column('summary', sa.Column('image_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('summary', 'image_type')
    op.drop_column('summary', 'image_file')
    op.add_column('link', sa.Column('image_link', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('link', 'image_type')
    op.drop_column('link', 'image_file')
    # ### end Alembic commands ###
