"""empty message

Revision ID: ca1e7cbe23f3
Revises: a8e0ca3b4af9
Create Date: 2020-06-22 15:00:57.556032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1e7cbe23f3'
down_revision = 'a8e0ca3b4af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('survey_author_id_fkey', 'survey', type_='foreignkey')
    op.create_foreign_key(None, 'survey', 'adminuser', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.create_foreign_key('survey_author_id_fkey', 'survey', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
