"""empty message

Revision ID: f613a23f2f69
Revises: 0647a8d4976b
Create Date: 2020-06-19 16:41:34.832048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f613a23f2f69'
down_revision = '0647a8d4976b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'route',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('origin', sa.String(length=100), nullable=False),
        sa.Column('target', sa.String(length=100), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
